// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:29d0a65c-b309-451a-ab58-b63e27959f62",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dxUn3VaIj",
    "aws_user_pools_web_client_id": "67i0li6sc23imoqe23n9irilo4",
    "oauth": {},
    "predictions": {
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "en",
                    "targetLanguage": "ro"
                }
            }
        },
        "identify": {
            "identifyText": {
                "proxy": false,
                "region": "us-east-2",
                "defaults": {
                    "format": "ALL"
                }
            }
        }
    }
};


export default awsmobile;
